spring.application.name=media-service
server.port=8080
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=25s
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OIDC_ISSUER:http://localhost:8180/realms/network}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${OIDC_JWKS:http://localhost:8180/realms/network/protocol/openid-connect/certs}
network.audience=network-api
management.server.port=9090
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=never
logging.structured.format.console=ecs
spring.datasource.url=${DB_URL:jdbc:oracle:thin:@//localhost:1521/FREEPDB1}
spring.datasource.username=${DB_USER:media_app}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=8
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.flyway.enabled=${MIGRATIONS_ENABLED:true}
spring.flyway.user=${DB_MIGRATION_USER:${spring.datasource.username}}
spring.flyway.password=${DB_MIGRATION_PASSWORD:${spring.datasource.password}}
spring.jackson.deserialization.fail-on-unknown-properties=true
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
logging.level.org.apache.kafka.common.config=WARN
management.endpoint.health.group.readiness.include=readinessState,db
spring.datasource.hikari.connection-init-sql=ALTER SESSION SET CURRENT_SCHEMA=${DB_SCHEMA:${spring.datasource.username}}
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA:${spring.datasource.username}}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
spring.servlet.multipart.file-size-threshold=0
